### PR TITLE
Updated guidelines for commentary type

### PR DESCRIPTION
**Pull request by sonofmun**

### CODE REVIEW

**Comment by sonofmun** [comment]
Take a look and let me know if there is anything that you don't like.
I will add the stuff for the structured metadata once you approve this one.

**Comment by PonteIneptique** [comment]
I think it lacks a description and an example of the `about` node :)

**Comment by sonofmun** [comment]
Oops. That is kind of important.
Check it now.

**Comment by PonteIneptique** [comment]
Because about and commentary are not defined by CTS, could you actually add a small paragraph outside of the code, such as 

```md
### Nodes specific to CapiTainS

#### Commentary

#### About
```

with what this represent and possibly the rationale behind it ?

**Comment by PonteIneptique** [comment]
Thanks !

**Pull request merged**
