### PR TITLE
First go for structured-metadata description

### PR DESCRIPTION
**Pull request by sonofmun**

### CODE REVIEW

**Comment by sonofmun** [comment]
I wanted to do a PR from my branch, but something went wrong. I will squash and merge once you approve.

**Comment by PonteIneptique** [comment]
Completely good except the namespace (my fault) which is http://purl.org/capitains/ns/1.0#

**Comment by PonteIneptique** [comment]
Perfect. You can squash

**Comment by sonofmun** [comment]
No, I can't. I don't have push access to this repo.

**Comment by PonteIneptique** [comment]
Now you can right ?

**Comment by sonofmun** [comment]
Ya, Baby!

**Pull request merged**
